# Generated by Django 4.1.3 on 2023-01-30 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_app', '0002_productmodels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodels',
            name='discription',
            field=models.CharField(max_length=100),
        ),
    ]
