# Generated by Django 4.1.3 on 2023-02-15 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_app', '0007_buy'),
    ]

    operations = [
        migrations.CreateModel(
            name='customercardM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardname', models.CharField(max_length=30)),
                ('cardnumber', models.IntegerField()),
                ('carddate', models.CharField(max_length=30)),
                ('scode', models.IntegerField()),
            ],
        ),
    ]
