# Generated by Django 4.1.3 on 2023-02-17 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_app', '0008_customercardm'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodels',
            name='shopid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
