# Generated by Django 4.1.3 on 2023-02-17 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_app', '0010_cart_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='userid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
