# Generated by Django 4.1.3 on 2023-05-17 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_app', '0012_shopnotification_usernotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_verified',
            field=models.BooleanField(default=True),
        ),
    ]
