# Generated by Django 4.1.3 on 2023-05-17 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_app', '0014_alter_profile_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_verified',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
